# MCP配置示例文件
# 用于 STDIO 或 SSE 连接模式

# STDIO 配置示例
# 对于 STDIO 模式，设置 mode: stdio 并提供 mcp_endpoint
# ---------------
# mode: stdio
# mcp_endpoint: wss://api.xiaozhi.me/mcp/?token=
# script_path: ip_get.py

# SSE 配置示例
# 对于 SSE 模式，设置 mode: sse 并同时提供 mcp_endpoint 和 sse_url
# ---------------
mode: sse
mcp_endpoint: wss://api.xiaozhi.me/mcp/?token=
sse_url: http://localhost:16100/12345/mcp/xiaozhi/sse