# MCP配置示例文件
# 用于 STDIO 或 SSE ，Streamable HTTP 连接模式

# STDIO 配置示例
# 对于 STDIO 模式，设置 mode: stdio 并提供 mcp_endpoint
# ---------------
# mode: stdio
# mcp_endpoint: wss://api.xiaozhi.me/mcp/?token=
# script_path: ip_get.py

# SSE 配置示例
# 对于 SSE 模式，设置 mode: sse 并同时提供 mcp_endpoint 和 sse_url
# ---------------
# mode: sse
# mcp_endpoint: wss://api.xiaozhi.me/mcp/?token=
# sse_url: http://localhost:16100/123456/mcp/xiaozhi/sse

# Streamable HTTP 配置示例
# 对于 Streamable HTTP 模式，设置 mode: streamable_http 并同时提供 mcp_endpoint 和 streamable_url
# ---------------
mode: streamable_http
mcp_endpoint: wss://api.xiaozhi.me/mcp/?token=
streamable_url: http://localhost:16100/123456/mcp/xiaozhi/mcp